version: '3'

services:
  web:
    container_name: webhelloworld
    image: crccheck/hello-world

  nginx:
    container_name: serverhelloworld
    restart: unless-stopped
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done'"
    environment:
      - CERTBOT_EMAIL=nghoangduong132@gmail.com
      - CERTBOT_DOMAIN=myshop.id.vn
    command: certonly --webroot --webroot-path=/var/www/certbot --force-renewal --email nghoangduong132@gmail.com -d myshop.id.vn --agree-tos
